# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
# no gaps after closing a window
set -g renumber-windows on

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# enable mouse control
set -g mouse on

# terminal graphics through tmux
set -gq allow-passthrough on

# don't rename windows automatically
set-option -g allow-rename off

# reload tmux
bind R source-file ~/.config/tmux/tmux.conf \; display-message "Tmux config reloaded!"

# readable messages, fresher status
set -g display-time 4000
set -g status-interval 5

# scrollback buffer
set -g history-limit 50000

# vim mode compatibility
set -s escape-time 0
set -s extended-keys on
bind-key -n C-BSpace send-keys C-w
set-option -g focus-events on

# true colors
set-option -g default-terminal 'tmux-256color'
set-option -sa terminal-features ',xterm-kitty:RGB'

# move between windows
bind C-l previous-window
bind C-u next-window
bind a last-window

# theme config
set -g @rosepine_window_use_single_color "yes"
set -g @rosepine_window_middle_separator " "
set -g @rosepine_window_inactive_color "thm_text"
set -g @rosepine_window_inactive_background_color "thm_overlay"

# restore sessions on server start
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Diaoul/rose-pine.tmux'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# must load last
set -g @plugin 'tmux-plugins/tmux-continuum'

# bootstrap tpm on first run
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# run plugins
run '~/.config/tmux/plugins/tpm/tpm'
