apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami
  pass_credentials_all: false
  password: ""
  url: https://charts.bitnami.com/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kasten
  pass_credentials_all: false
  password: ""
  url: https://charts.kasten.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: ingress-nginx
  pass_credentials_all: false
  password: ""
  url: https://kubernetes.github.io/ingress-nginx
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: rook-release
  pass_credentials_all: false
  password: ""
  url: https://charts.rook.io/release
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: vmware-tanzu
  pass_credentials_all: false
  password: ""
  url: https://vmware-tanzu.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: runix
  pass_credentials_all: false
  password: ""
  url: https://helm.runix.net
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: hajimari
  pass_credentials_all: false
  password: ""
  url: https://hajimari.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: emqx
  pass_credentials_all: false
  password: ""
  url: https://repos.emqx.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: external-dns
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/external-dns
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: diaoul
  pass_credentials_all: false
  password: ""
  url: https://diaoul.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: node-feature-discovery
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: oauth2-proxy
  pass_credentials_all: false
  password: ""
  url: https://oauth2-proxy.github.io/manifests
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: vector
  pass_credentials_all: false
  password: ""
  url: https://helm.vector.dev
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kyverno
  pass_credentials_all: false
  password: ""
  url: https://kyverno.github.io/kyverno/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: projectcalico
  pass_credentials_all: false
  password: ""
  url: https://projectcalico.docs.tigera.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: project-calico
  pass_credentials_all: false
  password: ""
  url: https://projectcalico.docs.tigera.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kubereboot
  pass_credentials_all: false
  password: ""
  url: https://kubereboot.github.io/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: descheduler
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/descheduler
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: openebs
  pass_credentials_all: false
  password: ""
  url: https://openebs.github.io/openebs
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: stevehipwell
  pass_credentials_all: false
  password: ""
  url: https://stevehipwell.github.io/helm-charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cilium
  pass_credentials_all: false
  password: ""
  url: https://helm.cilium.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: coredns
  pass_credentials_all: false
  password: ""
  url: https://coredns.github.io/helm
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: postfinance
  pass_credentials_all: false
  password: ""
  url: https://postfinance.github.io/kubelet-csr-approver
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bjw-s
  pass_credentials_all: false
  password: ""
  url: https://bjw-s-labs.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: k8s_gateway
  pass_credentials_all: false
  password: ""
  url: https://k8s-gateway.github.io/k8s_gateway/
  username: ""
