after-startup-command = [
    'exec-and-forget sketchybar',
    'exec-and-forget borders',
    'exec-and-forget ./scripts/workspaces.sh'
]
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 16
    inner.vertical =   16
    outer.left =       16
    outer.bottom =     16
    outer.top =        52
    outer.right =      16

#[workspace-to-monitor-force-assignment]
#    1 = '^built-in retina display$'
#    2 = '^built-in retina display$'
#    3 = '^built-in retina display$'
#    4 = ['main', '^built-in retina display$']
#    5 = [ 'main', '^built-in retina display$' ]
#    6 = [ 'main', '^built-in retina display$' ]
#    7 = [ 'main', '^built-in retina display$' ]
#    8 = [ 'pa248', '^built-in retina display$' ]
#    9 = [ 'pa248', '^built-in retina display$' ]
#    10 = [ 'pa248', '^built-in retina display$' ]

[mode.main.binding]
    # Focus
    ## Nodes
    alt-m = 'focus --boundaries all-monitors-outer-frame left'
    alt-n = 'focus --boundaries all-monitors-outer-frame down'
    alt-e = 'focus --boundaries all-monitors-outer-frame up'
    alt-i = 'focus --boundaries all-monitors-outer-frame right'
    ## Workspaces
    alt-u = 'workspace next'
    alt-l = 'workspace prev'
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    # Move
    alt-shift-m = 'move left'
    alt-shift-n = 'move down'
    alt-shift-e = 'move up'
    alt-shift-i = 'move right'
    alt-shift-ctrl-m = 'move-node-to-monitor --focus-follows-window left'
    alt-shift-ctrl-i = 'move-node-to-monitor --focus-follows-window right'
    alt-shift-u = [ 'move-node-to-workspace next', 'workspace next' ]
    alt-shift-l = [ 'move-node-to-workspace prev', 'workspace prev' ]
    alt-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
    alt-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
    alt-shift-3 = 'move-node-to-workspace --focus-follows-window 3'
    alt-shift-4 = 'move-node-to-workspace --focus-follows-window 4'
    alt-shift-5 = 'move-node-to-workspace --focus-follows-window 5'
    alt-shift-6 = 'move-node-to-workspace --focus-follows-window 6'
    alt-shift-7 = 'move-node-to-workspace --focus-follows-window 7'
    alt-shift-8 = 'move-node-to-workspace --focus-follows-window 8'
    alt-shift-9 = 'move-node-to-workspace --focus-follows-window 9'
    alt-shift-0 = 'move-node-to-workspace --focus-follows-window 10'

    # Utils
    alt-backtick = 'workspace-back-and-forth'
    alt-j = 'fullscreen --no-outer-gaps'
    alt-w = 'close'
    alt-q = 'close --quit-if-last-window'
    alt-cmd-r = 'reload-config'
    alt-enter = 'exec-and-forget open -n /Applications/kitty.app'
