# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# Example config and default values
#
# [[item]]
# file = '~/.config/example' (file to inject to, supports tilde and env var expansion. required)
# template = 'example' (template to use. required)
# subtemplate = 'default' (subtemplate to use)
# rewrite = false (should we rewrite the entire file?)
# start = '# Start flavours' (if not rewriting, where to start replacing)
# end = '# End flavours' (if not rewriting, where to stop replacing)
# hook = '' (command to execute after injecting)

[[item]]
file = '~/.config/kitty/theme.conf'
template = 'kitty'
subtemplate = 'default-256'
rewrite = true

[[item]]
file = '~/.config/alacritty/alacritty.yml'
template = 'alacritty'
subtemplate = 'default-256'
