#!/usr/bin/env bash
# Shared helpers for the aerospace workspace items.
#
# Two rules keep the workspace strip cheap to update:
#   - every sketchybar mutation is accumulated in SB_ARGS and flushed with a
#     single sketchybar call, so a workspace switch is one IPC round trip
#   - window state is read with one `aerospace list-windows --all`, and app
#     icons are resolved through a sourced function instead of a subprocess

SB_ARGS=()

DISPLAY_FINGERPRINT_FILE=${SKETCHYBAR_DISPLAY_FINGERPRINT:-/tmp/sketchybar-displays.fingerprint}

# Left behind by display_change.sh when a redistribution did not land, so that
# the --reload it triggers on the way out does not record the new arrangement as
# handled — the stale fingerprint is what makes the next display_change retry
# instead of dismissing itself as a no-op. Consumed by the rebuild it guards.
DISPLAY_RETRY_FILE=${SKETCHYBAR_DISPLAY_RETRY:-/tmp/sketchybar-displays.retry}

# Identity of the current monitor arrangement: the display frames, ordered
# left-to-right. Used to tell a real arrangement change (dock, undock,
# resolution change) apart from a mere change of *active* display, which
# sketchybar reports through the same display_change event.
display_fingerprint() {
  sketchybar --query displays | jq -c 'sort_by(.frame.x, .frame.y) | map(.frame)'
}

save_display_fingerprint() {
  display_fingerprint > "$DISPLAY_FINGERPRINT_FILE"
}

# Record the arrangement the workspace items were just built against, unless a
# failed redistribution asked for the previous one to be kept so it retries.
save_display_fingerprint_unless_retry() {
  if [[ -f $DISPLAY_RETRY_FILE ]]; then
    rm -f "$DISPLAY_RETRY_FILE"
    return 0
  fi
  save_display_fingerprint
}

# Scripts are spawned by the sketchybar daemon and inherit *its* environment, so
# exporting SKETCHYBAR_DEBUG in an interactive shell has no effect. Set it where
# the daemon itself is started, in aerospace's after-startup-command:
#   exec-and-forget /bin/bash -c "SKETCHYBAR_DEBUG=1 sketchybar --reload || SKETCHYBAR_DEBUG=1 sketchybar"
sb_log() {
  [[ -n ${SKETCHYBAR_DEBUG:-} ]] || return 0
  echo "$(date '+%H:%M:%S') $*" >> "${SKETCHYBAR_LOG:-/tmp/sketchybar.log}"
}

sb_flush() {
  (( ${#SB_ARGS[@]} )) || return 0
  # ease the pill colours rather than snapping them; --animate applies to the
  # whole chain that follows, so one prefix covers every queued --set
  sketchybar --animate sin4 12 "${SB_ARGS[@]}"
  SB_ARGS=()
}

# Apps upstream has no glyph for, which would otherwise all collapse onto the
# same :default: square and stop distinguishing what a workspace holds.
#
# Keyed on aerospace's %{app-name}. Values must be tokens the *installed*
# sketchybar-app-font actually ships, since an unknown one renders as a missing
# glyph rather than falling back; list what is available with
#   grep -o 'icon_result=":[a-z0-9_]*:"' plugins/icon_map_fn.sh | sort -u
# This lives here rather than in icon_map_fn.sh because that file is generated
# and regenerating it would drop the edits.
declare -A ICON_OVERRIDE=(
  [Quill]=":notes:"
  # no :calculator: token exists; :numbers: is the closest numeric glyph
  [Calculator]=":numbers:"
)

load_icon_map() {
  declare -F icon_map >/dev/null && return 0
  # icon_map_fn.sh is generated by sketchybar-app-font and ends with a
  # self-invocation. Sourcing it with an empty argument and discarding that
  # output leaves icon_map() defined, which avoids forking a bash process and
  # reparsing 400+ case branches once per window.
  source "$CONFIG_DIR/plugins/icon_map_fn.sh" "" >/dev/null

  # Regenerating icon_map_fn.sh from upstream could change that trailing shape;
  # without this guard icon_result would stay empty and every workspace label
  # would silently go blank.
  declare -F icon_map >/dev/null && return 0
  sb_log "icon_map undefined after sourcing icon_map_fn.sh; regenerate it"
  icon_map() { icon_result=":default:"; }
}

# WS_STATE[workspace] = focused | visible | hidden
#
# Visibility and focus are separate in aerospace: every monitor has one visible
# workspace, but only one of those holds the keyboard. On a single monitor the
# two always coincide, so this only shows up once a second screen is attached.
build_workspace_states() {
  local workspace visible focused monitor
  local -A monitor_of=()

  declare -gA WS_STATE=()
  while IFS='|' read -r workspace visible focused monitor; do
    monitor_of["$workspace"]=$monitor
    if [[ $focused == true ]]; then
      WS_STATE["$workspace"]=focused
    elif [[ $visible == true ]]; then
      WS_STATE["$workspace"]=visible
    else
      WS_STATE["$workspace"]=hidden
    fi
  done < <(aerospace list-workspaces --all \
    --format '%{workspace}|%{workspace-is-visible}|%{workspace-is-focused}|%{monitor-id}')

  # exec-on-workspace-change fires while the switch is still settling, so the
  # queried focus and visibility lag by one event and the strip would render the
  # previous state. The trigger's own env var is authoritative, so when it is
  # present it wins: whatever it names is focused, whatever else the query
  # claimed was focused is merely visible on its own monitor, and anything else
  # that claimed to be visible on the *same* monitor has just been replaced.
  [[ -n ${FOCUSED_WORKSPACE:-} ]] || return 0

  local target_monitor=${monitor_of[$FOCUSED_WORKSPACE]:-}
  for workspace in "${!WS_STATE[@]}"; do
    [[ $workspace == "$FOCUSED_WORKSPACE" ]] && continue
    case "${WS_STATE[$workspace]}" in
      focused) WS_STATE["$workspace"]=visible ;;
      visible)
        [[ ${monitor_of[$workspace]} == "$target_monitor" ]] &&
          WS_STATE["$workspace"]=hidden
        ;;
    esac
  done
  WS_STATE["$FOCUSED_WORKSPACE"]=focused
}

get_workspace_to_monitor_id() {
  [[ -n ${_WORKSPACE_TO_MONITOR_LOADED:-} ]] && return 0

  # aerospace monitor-id and sketchybar display frames are both ordered
  # left-to-right; NSScreen appkit ids are not, so they can't be used here
  local -a arrangement_ids=()
  local id workspace monitor
  while IFS= read -r id; do
    arrangement_ids+=("$id")
  done < <(sketchybar --query displays | jq -r 'sort_by(.frame.x, .frame.y) | .[]."arrangement-id"')

  declare -gA WORKSPACE_TO_MONITOR_ID=()
  while IFS='|' read -r workspace monitor; do
    WORKSPACE_TO_MONITOR_ID["$workspace"]="${arrangement_ids[monitor - 1]}"
  done < <(aerospace list-workspaces --all --format '%{workspace}|%{monitor-id}')

  _WORKSPACE_TO_MONITOR_LOADED=1
}

# WS_ICONS[workspace] = app icon glyphs for every window on that workspace
build_workspace_icons() {
  load_icon_map

  local workspace app glyph
  declare -gA WS_ICONS=()
  while IFS='|' read -r workspace app; do
    glyph=${ICON_OVERRIDE[$app]:-}
    if [[ -n $glyph ]]; then
      icon_result=$glyph
    else
      icon_map "$app"
    fi
    # separate glyphs without a trailing separator: a trailing one would pad the
    # right of every pill and leave it visibly lopsided against its left inset
    [[ -n ${WS_ICONS[$workspace]:-} ]] && WS_ICONS["$workspace"]+="  "
    WS_ICONS["$workspace"]+="$icon_result"
  done < <(aerospace list-windows --all --format '%{workspace}|%{app-name}')
}

# Queue label, colors and pill style for one workspace. Requires
# build_workspace_icons and build_workspace_states to have run first.
queue_workspace() {
  local sid=$1
  local icons=${WS_ICONS[$sid]:-}
  local label_drawing=off fg bg border_width
  # with no label, icon.padding_right becomes the pill's right edge rather than
  # the gap before the label, so it has to match icon.padding_left
  local icon_padding_right=11

  # keep empty workspaces visible, but without an empty label box
  if [[ -n $icons ]]; then
    label_drawing=on
    icon_padding_right=7
  fi

  # Tiers, separated on both glyph colour and pill treatment:
  #   focused  filled rose pill — the only filled accent on the whole bar
  #   visible  rose glyphs, 1px rose outline: live on its own monitor, not
  #            holding the keyboard
  #   hidden   plain pill; rose if it is holding windows, muted if it is empty,
  #            so the workspaces with nothing in them are the ones that recede
  #
  # The border is inset, so an outlined pill's fill is 1px smaller all round than
  # its neighbours'. Left as-is deliberately: compensating for it means growing
  # the box, which shifts the strip every time focus moves between monitors.
  case "${WS_STATE[$sid]:-hidden}" in
    focused)
      fg=$BASE
      bg=$ROSE
      border_width=0
      ;;
    visible)
      fg=$ROSE
      bg=$OVERLAY
      border_width=1
      ;;
    *)
      # $icons is empty exactly when the workspace holds no windows
      if [[ -n $icons ]]; then
        fg=$ROSE
      else
        fg=$SUBTLE_LIGHT
      fi
      bg=$OVERLAY
      border_width=0
      ;;
  esac

  SB_ARGS+=(--set "space.$sid"
    label="$icons"
    label.drawing="$label_drawing"
    label.color="$fg"
    icon.color="$fg"
    icon.padding_right="$icon_padding_right"
    background.color="$bg"
    background.border_color="$ROSE"
    # always set, so a pill leaving the outlined tier loses its border
    background.border_width="$border_width")
}

# Resync every workspace, not only the focused one, so a window opening on a
# workspace you are not looking at still updates its icons.
sync_workspaces() {
  local sid

  build_workspace_states
  build_workspace_icons

  # order is irrelevant for --set, and iterating the state map saves a third
  # aerospace call
  for sid in "${!WS_STATE[@]}"; do
    queue_workspace "$sid"
  done

  sb_flush
}

create_workspace() {
  local sid=$1
  local monitor_id

  get_workspace_to_monitor_id

  monitor_id=${WORKSPACE_TO_MONITOR_ID[$sid]}
  sb_log "creating workspace $sid on display $monitor_id"

  SB_ARGS+=(--add item "space.$sid" left
    --set "space.$sid"
      display="$monitor_id"
      icon="$sid"
      # outer insets match (11 each side); the inner gap between the workspace
      # number and the app glyphs is icon.padding_right + label.padding_left
      icon.padding_left=11
      label.font="sketchybar-app-font:Regular:16.0"
      label.padding_left=5
      label.padding_right=11
      click_script="aerospace workspace $sid")

  queue_workspace "$sid"
}
