#! /bin/sh
./.fehbg &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backends &
pgrep -x polybar > /dev/null || polybar main &
pgrep -x xautolock > /dev/null || xautolock -time 60 -locker "systemctl suspend" &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-1 -d VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colors
bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#fe8019"

bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^7' state=floating
