#!/bin/bash
# wallpaper
./.fehbg &

# hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# compositor
pgrep -x picom > /dev/null || picom --experimental-backends &

# bspc config
bspc config border_width              2
bspc config window_gap                16
bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config normal_border_color       "#282828"
bspc config active_border_color       "#ebdbb2"
bspc config focused_border_color      "#fe8019"
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true

# desktops
.config/bspwm/dynamic-monitor-desktops.sh

# polybar
.config/polybar/launch.sh
