#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# theme
source "$CONFIG_DIR/colors.sh"

bar=(
  position=top
  height=36
  margin=16
  y_offset=8
  corner_radius=10
  blur_radius=30
  color="$BAR_COLOR"
)
sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.font="CaskaydiaCove Nerd Font:Bold:17.0"
  icon.color="$ACCENT_COLOR"
  icon.padding_left=6
  icon.padding_right=4
  label.font="CaskaydiaCove Nerd Font:Bold:17.0"
  label.color="$ACCENT_COLOR"
  label.padding_left=4
  label.padding_right=6
  background.color="$BACKGROUND_LIGHT"
  background.corner_radius=5
  background.height=24
  background.drawing=off
)
sketchybar --default "${default[@]}"

# load items
# source "$CONFIG_DIR/items/apple.sh"
source "$CONFIG_DIR/items/workspaces.sh"
source "$CONFIG_DIR/items/front_app.sh"
source "$CONFIG_DIR/items/datetime.sh"
source "$CONFIG_DIR/items/volume.sh"
source "$CONFIG_DIR/items/battery.sh"
source "$CONFIG_DIR/items/slack.sh"

sketchybar --update
