name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Copy pre-commit configuration
        run: cp .github/workflows-config/.pre-commit-config.yaml ./
      - uses: pre-commit/action@v2.0.0
