[[themes]]
name = "gruvbox"
[themes.palette]
background = "#282828"
foreground = "#ebdbb2"
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"
[themes.component_style]
block_title = { fg = "Cyan"  }
border = {}
playback_track = { fg = "Yellow", modifiers = ["Bold"] }
playback_artists = { fg = "Yellow", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar = { bg = "BrightBlack", fg = "Green" }
current_playing = { fg = { Rgb = { r = 254, g = 128, b = 25}}, modifiers = ["Bold"] }
page_desc = { fg = "Magenta", modifiers = ["Bold", "Italic"] }
table_header = { fg = "Blue" }
selection = { modifiers = ["Bold", "Reversed"] }
